- name: Radius global
  nxos_aaa_server:
    state: present
    server_type: radius
    deadtime: "{{ aaa_vars.deadtime | default(omit) }}"
    directed_request: "{{ aaa_vars.directed_request | default(omit) }}"
  when: >
    ansible_network_os == 'nxos' 
  tags: 
    - aaa_config
    - radius_config
    - nxos

- name: Tacacs global
  nxos_aaa_server:
    state: present
    server_type: tacacs
    deadtime: "{{ aaa_vars.deadtime | default(omit) }}"
    directed_request: "{{ aaa_vars.directed_request | default(omit) }}"
  when: >
    ansible_network_os == 'nxos' 
  tags: 
    - aaa_config
    - tacacs_config
    - nxos

- name: Tacacs group
  nxos_config:
    lines: 
      - server {{ item.ip | default(item.name) }}
      - source-interface {{ aaa_vars.source_interface | default('loopback 0') }}
    parents: aaa group server tacacs+ {{ aaa_vars.tacacs_group_name | mandatory }}
  with_items: "{{ aaa_servers }}"    
  when: >
    ansible_network_os == 'nxos' 
  tags: 
    - aaa_config
    - tacacs_config
    - nxos

- name: aaa central auth
  nxos_config:
    lines: 
      - aaa authentication login default group {{ aaa_vars.tacacs_group_name | default(aaa_vars.radius_group_name) }} {{ no_local | default('local') }}
      - aaa authentication login console group {{ aaa_vars.console_group | default('local') }}    
      - aaa authentication login error-enable
      - aaa authentication login ascii-authentication        
    parents:    
  when: >
    ansible_network_os == 'nxos' and
    aaa_vars.only_local != True
  tags: 
    - aaa_config    
    - nxos